=== brunoguimas/metapps/docs/arquitetura/tarefas/quiz.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "QuizTask",
    "type": "object",
    "required": [
        "title",
        "type",
        "description",
        "expectation",
        "questions"
    ],
    "properties": {
        "title": {
            "type": "string",
            "minLength": 3
        },
        "type": {
            "type": "string",
            "const": "quiz"
        },
        "description": {
            "type": "string"
        },
        "expectation": {
            "type": "string"
        },
        "questions": {
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "object",
                "required": [
                    "question",
                    "type",
                    "answer"
                ],
                "properties": {
                    "material": {
                        "type": "string"
                    },
                    "question": {
                        "type": "string",
                        "minLength": 3
                    },
                    "type": {
                        "type": "string",
                        "enum": [
                            "options",
                            "text"
                        ]
                    },
                    "options": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "minItems": 2
                    },
                    "explanation": {
                        "type": "string"
                    },
                    "answer": {
                        "oneOf": [
                            {
                                "type": "integer",
                                "minimum": 0
                            },
                            {
                                "type": "string"
                            }
                        ]
                    }
                },
                "allOf": [
                    {
                        "if": {
                            "properties": {
                                "type": {
                                    "const": "options"
                                }
                            }
                        },
                        "then": {
                            "required": [
                                "options"
                            ],
                            "properties": {
                                "answer": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    {
                        "if": {
                            "properties": {
                                "type": {
                                    "const": "text"
                                }
                            }
                        },
                        "then": {
                            "properties": {
                                "answer": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ]
            }
        }
    },
    "additionalProperties": false
}

=== brunoguimas/metapps/docs/arquitetura/tarefas/quiz.example.json
{
    "title": "Quiz comandos básicos POSTGRESQL",
    "type": "quiz",
    "description": "Responda o quiz assinalando as alternativas corretas",
    "expectation": "Compreender comandos simples para operar no banco de dados postgressql, o aluno deve ser capaz de compreender comandos simples para realizar operações CRUD em um banco de dados postgresql",
    "questions": [
        {
            "material": "Bruno estava operando no banco de dados da empresa, quando se deparou com uma situação em que precisava cadastrar um usuário manualmente. Os usuários deste sistema contém 3 campos simples: Email e Senha. Bruno precisava cadastrar manualmente um usuário com as seguintes credenciais: jorge@gmail.com, senha1234",
            "question": "Qual alternativa demonstra como inserir os valores mostrados na tabela de usuário?",
            "type": "options",
            "options": [
                "SELECT * FROM usuarios;",
                "INSERT usuarios jorge@gmail.com, senha1234",
                "INSERT INTO usuarios (email, senha) VALUES ('jorge@gmail.com', 'senha1234')"
            ],
            "explanation": "Para um banco de dados PostgreSQL utilizamos o comando 'INSERT INTO' para inserir usuários.",
            "answer": 2
        },
        {
            "question": "Qual comando Bruno deve usar para vizualizar todos os usuários?",
            "type": "options",
            "options": [
                "SELECT * FROM usuarios",
                "DELETE FROM usuarios",
                "BEGIN TRAN"
            ],
            "explanation": "Para um banco de dados PostgreSQL utilizamos o comando 'SELECT {campos}' para inserir usuários.",
            "answer": 0
        },
        {
            "question": "Como deletar todas as linhas de uma tabela 'tarefas'?",
            "type": "text",
            "explanation": "Para deletar todas as linhas de uma tabela utilizamos o comando DELETE FROM",
            "answer": "DELETE FROM tarefas;"
        }
    ]
}
